create database DBTEAM

GO

USE DBTEAM

GO

CREATE TABLE AGENTE(
CODIGO VARCHAR (5),
NOMBRE VARCHAR (50),
EDAD INT, 
TELEFONO INT
);
GO

CREATE PROC SP_LISTAR_AGENTE
AS
SELECT * FROM AGENTE ORDER BY CODIGO
GO

CREATE PROC SP_BUSCAR_AGENTE
@NOMBRE VARCHAR(50)
AS
SELECT CODIGO,NOMBRE,EDAD,TELEFONO FROM AGENTE WHERE NOMBRE LIKE @NOMBRE + '%'
GO

CREATE PROC SP_MANTENIMIENTO_AGENTE
@CODIGO VARCHAR(5),
@NOMBRE VARCHAR(50),
@EDAD INT,
@TELEFONO INT,
@ACCION VARCHAR(50) OUTPUT
AS
IF (@ACCION='1')
BEGIN
     DECLARE @CODNUEVO VARCHAR(5), @CODMAX VARCHAR(5)
	 SET @CODMAX = (SELECT MAX(CODIGO) FROM AGENTE)
	 SET @CODMAX = ISNULL (@CODMAX, 'A0000')
	 SET @CODNUEVO = 'A' +RIGHT(RIGHT(@CODMAX, 4)+10001,4)
	 INSERT INTO AGENTE(CODIGO,NOMBRE,EDAD,TELEFONO)
	 VALUES(@CODNUEVO,@NOMBRE,@EDAD,@TELEFONO)
	 SET @ACCION='Se genero el codigo: ' + @codnuevo
end
else if (@ACCION='2')
BEGIN
     UPDATE AGENTE SET NOMBRE=@NOMBRE, EDAD=@EDAD, TELEFONO=@TELEFONO WHERE CODIGO=@CODIGO  
	 SET @ACCION='Se Modifico el codigo: ' +@CODIGO
END
ELSE IF (@ACCION='3')
BEGIN
	 DELETE FROM AGENTE WHERE CODIGO=@CODIGO
	 SET @ACCION='Se Borro el codigo: ' +@CODIGO
END
GO





